name: Progress Bar CI

on:
  push:
    branches: master
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Update Quotes.txt
      run: node index.js
    - name: Commit change & Push
      run: |
          git config user.name 'Losttrack21'
          git config user.email 'shubhansukumar563@gmail.com'
          git commit -am "plant some tree 🌳"
          git push
